### PR TITLE
In a situation where there is a type conflict and you have an …

### PR DESCRIPTION
**Pull request by CH-EricLundberg**
… explicit resolver, add option to prefer the resolver

### CODE REVIEW

**Comment by CH-EricLundberg** [comment]
Not sure if this is the best way to solve my issue but it seems to work.  Happy to see if there are better places to put in this kind of check, I'm new to kotlin and this codebase.

**Comment by CH-EricLundberg** [comment]
@oliemansm what do you think of this approach?

**Comment by CH-EricLundberg** [comment]
@apottere (or anyone) is this project being maintained anymore?  It feels very quiet.  If it is I would love to get some feedback on the PR. :)

**Comment by oliemansm** [comment]
Thanks @CH-EricLundberg!

**Comment by CH-EricLundberg** [comment]
Right on.  And looks like there is a decent cadence on the release train, I'll keep my eye out for the next one so I can delete the local version. :)

**Pull request merged**
